version: "3.8"
name: dog-club
services:

  postgres:
    image: postgres:16-alpine
    container_name: dog-club-postgres
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    ports:
      - "5432:5432"